import { createContext, useContext, useState } from "react";
import type { ReactNode } from "react";

export type Language = "id" | "en";

export const translations = {
  id: {
    // Navigation & Common
    back: "Kembali",
    back_to_dashboard: "Kembali ke Dashboard",
    back_to_profile: "Kembali ke Profil",
    dashboard: "Beranda",
    activities: "Manajemen Kegiatan",
    assignments: "Penugasan Khusus",
    production: "Produksi Konten",
    review_approval: "Review & Persetujuan",
    media_pub: "Publikasi Media",
    content_bank: "Bank Konten",
    reports_stats: "Laporan & Statistik",
    member_list: "Daftar Anggota",
    add_officer: "Tambah Petugas",
    my_assignments: "Penugasan Saya",
    available_agenda: "Agenda Tersedia",
    profile: "Profil",
    profile_mine: "Profil Saya",
    settings: "Pengaturan",
    account_settings: "Pengaturan Akun",
    logout: "Keluar",
    logout_confirm_title: "Konfirmasi Keluar",
    logout_confirm_desc: "Apakah Anda yakin ingin mengakhiri sesi akun ini?",
    cancel: "Batal",
    yes_logout: "Ya, Keluar",
    help: "Bantuan",
    notifications: "Notifikasi",
    system_active: "Sistem SIMIKP Aktif",
    verified_account: "Akun Terverifikasi",
    save: "Simpan",
    saving: "Menyimpan...",
    save_changes: "Simpan Perubahan",
    delete: "Hapus",
    edit: "Edit",
    add: "Tambah",
    search: "Cari",
    filter: "Filter",
    all: "Semua",
    status: "Status",
    actions: "Aksi",
    details: "Detail",
    close: "Tutup",
    success: "Berhasil",
    error: "Terjadi Kesalahan",
    warning: "Peringatan",
    info: "Informasi",
    loading: "Memuat...",
    confirm: "Konfirmasi",
    priority: "Prioritas",
    high: "Tinggi",
    medium: "Sedang",
    low: "Rendah",
    deadline: "Tenggat Waktu",
    location: "Lokasi",
    date: "Tanggal",
    month: "Bulan",
    year: "Tahun",
    notes: "Catatan",
    upload: "Unggah",
    download: "Unduh",
    preview: "Pratinjau",
    views: "Tayangan",
    active: "Aktif",
    pending: "Pending",
    done: "Selesai",
    in_progress: "Dalam Proses",
    conflict: "Bentrok",
    revision: "Revisi",
    approved: "Disetujui",
    need_review: "Menunggu Review",
    select_all: "Pilih Semua",
    clear_filter: "Reset Filter",
    refresh: "Segarkan",
    today: "Hari Ini",

    // Roles & Divisions
    role_super_admin: "Super Admin",
    role_ahli_pertama: "Pranata Ahli Pertama",
    role_admin: "Admin",
    role_manager: "Manager",
    role_staff: "Staff",
    role_reviewer: "Reviewer",
    role_petugas: "Petugas Lapangan",
    bidang_ahli_pertama: "Pengawas Fungsional Ahli Pertama",
    bidang_prahum: "Pranata Humas / Naskah",
    bidang_foto: "Fotografi & Visual",
    bidang_video: "Videografi & Reels",
    bidang_desainer: "Desain Grafis & Editor",
    bidang_reporter: "Reporter Lapangan",
    bidang_kontributor: "Kontributor Berita",
    ahli_supervision: "Supervisi & Verifikasi Ahli",
    ahli_executive_dashboard: "Panel Supervisi Ahli Pertama",
    ahli_strategic_validation: "Telaah & Pengesahan Strategis",
    ahli_sla_metrics: "Capaian SLA & Validasi Naskah",

    // Dashboard Page
    dash_total_activities_month: "Total Kegiatan Bulan Ini",
    dash_tasks_in_progress: "Tugas Dalam Proses",
    dash_content_ready_review: "Konten Siap Review",
    dash_published_success: "Publikasi Sukses",
    dash_total_files_bank: "Total File di Bank Konten",
    dash_recent_tasks_deadline: "Tugas Terbaru & Deadline Mendekati",
    dash_activity_calendar: "Kalender Kegiatan",
    dash_activity_calendar_desc: "Pilih tanggal untuk melihat daftar kegiatan di hari tersebut.",
    dash_view_all_activities: "Lihat Semua Kegiatan",
    dash_col_activity: "Nama Kegiatan",
    dash_col_content_type: "Jenis Konten",
    dash_col_officer: "Petugas",
    dash_col_organizer: "Penyelenggara",
    dash_col_deadline: "Deadline",
    dash_col_status: "Status",
    dash_panel_prahum_title: "PRAHUM / Rilis",
    dash_panel_prahum_subtitle: "Peliputan & Pembuatan Naskah Berita",
    dash_panel_foto_title: "FOTO",
    dash_panel_foto_subtitle: "Liputan Dokumentasi Visual & Foto Rilis",
    dash_panel_video_title: "VIDEO & REELS",
    dash_panel_video_subtitle: "Produksi Video Berita & Konten Sosmed",
    dash_panel_desain_title: "DESAINER GRAFIS",
    dash_panel_desain_subtitle: "Infografis, Banner, & Visual Sosmed",
    dash_status_peliputan: "Peliputan",
    dash_status_draft: "Draft Naskah",
    dash_status_siap_rilis: "Siap Rilis",
    dash_status_take_shoot: "Take Shoot",
    dash_status_raw_photo: "Bahan Mentah",
    dash_status_editing: "Editing",
    dash_status_reels: "Reels / TikTok",
    dash_status_infografis: "Desain Infografis",
    dash_status_banner: "Banner / Poster",
    dash_status_revisi_desain: "Revisi Desain",
    dash_activity_details: "Detail Kegiatan & Agenda",
    dash_no_activities_today: "Belum ada kegiatan pada tanggal ini.",
    dash_no_activities_db: "Belum ada kegiatan terjadwal di database.",
    dash_manage_in_activities: "Kelola di Manajemen Kegiatan",
    dash_prod_workflow_status: "Status Alur Kerja Produksi",
    dash_volume_per_opd: "Volume Kegiatan per OPD",
    dash_total_running_tasks: "Total tugas berjalan",

    // Kegiatan Page
    kegiatan_title: "Agenda Kegiatan",
    kegiatan_subtitle: "Kelola jadwal kegiatan (Satu Kegiatan = Satu Data Induk)",
    kegiatan_add_btn: "Tambah Kegiatan",
    kegiatan_add_modal_title: "Tambah Kegiatan Baru",
    kegiatan_edit_modal_title: "Edit Data Kegiatan",
    kegiatan_search_placeholder: "Cari nama kegiatan...",
    kegiatan_filter_all_time: "Semua Waktu",
    kegiatan_filter_today: "Hari Ini",
    kegiatan_filter_tomorrow: "Besok",
    kegiatan_filter_this_week: "Minggu Ini",
    kegiatan_col_title: "Nama Kegiatan",
    kegiatan_col_date: "Tanggal Pelaksanaan",
    kegiatan_col_location: "Lokasi",
    kegiatan_col_opd: "OPD Penyelenggara",
    kegiatan_col_output: "Output Konten",
    kegiatan_col_priority: "Prioritas",
    kegiatan_col_status: "Status",
    kegiatan_col_action: "Aksi",
    kegiatan_form_title: "Nama Kegiatan",
    kegiatan_form_title_ph: "Contoh: Rapat Koordinasi SPBE...",
    kegiatan_form_date: "Tanggal Pelaksanaan",
    kegiatan_form_location_detail: "Detail Lokasi Pelaksanaan",
    kegiatan_form_building: "Nama Gedung / Ruangan *",
    kegiatan_form_district: "Kecamatan",
    kegiatan_form_subdistrict: "Kelurahan / Desa",
    kegiatan_form_address: "Alamat Lengkap (Opsional)",
    kegiatan_form_opd: "OPD Penyelenggara",
    kegiatan_form_opd_ph: "Pilih atau ketik OPD (Contoh: Diskominfo / Dinkes)",
    kegiatan_form_priority: "Prioritas",
    kegiatan_form_outputs_title: "Output yang Dibutuhkan (Berdasarkan Jabatan)",
    kegiatan_form_manage_outputs: "Kelola Output",
    kegiatan_form_selected_count: "dipilih",
    kegiatan_form_related_assignments: "Penugasan Khusus Terkait",
    kegiatan_form_add_assignment: "+ Tambah Penugasan",
    kegiatan_form_no_assigned_staff: "Belum ada staf yang ditugaskan untuk kegiatan ini.",
    kegiatan_empty: "Tidak ada kegiatan ditemukan.",
    kegiatan_delete_confirm: "Hapus kegiatan ini? Tindakan ini tidak bisa dibatalkan.",
    kegiatan_manage_outputs_title: "Kelola Pilihan Output Kegiatan",
    kegiatan_add_new_output_title: "Tambah Tipe Output Baru",
    kegiatan_output_name_label: "Nama Tipe Output",
    kegiatan_output_name_ph: "Contoh: Live Streaming, Podcast, Press Release...",
    kegiatan_select_role_label: "Pilih Jabatan / Penanggung Jawab",
    kegiatan_reset_default_btn: "Reset ke Bawaan",
    kegiatan_finish_btn: "Selesai",
    kegiatan_current_outputs_list: "Daftar Output Saat Ini",
    kegiatan_options_count: "Pilihan",
    kegiatan_no_output_options: "Tidak ada pilihan output",
    kegiatan_no_output_for_role: "Belum ada output",
    kegiatan_edit_output_title: "Edit & Pindahkan Tipe Output",
    kegiatan_move_to_other_role: "Pindahkan ke Jabatan Lain",
    kegiatan_cal_subtitle: "Pilih tanggal untuk melihat atau menambahkan kegiatan baru",

    // Penugasan Page
    penugasan_title: "Penugasan Khusus",
    penugasan_subtitle: "Kelola dan pantau jadwal liputan penugasan staf konten dengan data yang rapi dan terorganisir.",
    penugasan_add_btn: "Tugas Baru",
    penugasan_search_ph: "Cari kegiatan, staf, jenis...",
    penugasan_filter_bidang: "Semua Sektor / Bidang",
    penugasan_stat_total: "Total Penugasan",
    penugasan_stat_progress: "Sedang Berjalan",
    penugasan_stat_conflict: "Potensi Bentrok Jadwal",
    penugasan_stat_done: "Tugas Selesai",
    penugasan_tab_all: "Semua",
    penugasan_tab_in_progress: "Proses",
    penugasan_tab_done: "Selesai",
    penugasan_tab_pending: "Menunggu",
    penugasan_tab_conflict: "Bentrok",
    penugasan_sort_label: "Urutkan:",
    penugasan_sort_activity: "Kegiatan",
    penugasan_sort_time: "Waktu",
    penugasan_sort_status: "Status",
    penugasan_col_officer: "Petugas",
    penugasan_col_content_type: "Jenis Konten",
    penugasan_col_time: "Waktu",
    penugasan_col_status: "Status",
    penugasan_col_action: "Aksi",
    penugasan_add_officer_btn: "Tambah Petugas",
    penugasan_officers_count: "petugas",
    penugasan_empty: "Tidak ada penugasan ditemukan",
    penugasan_empty_desc: "Coba ganti filter tab atau kata kunci pencarian.",
    penugasan_bulk_selected: "dipilih:",
    penugasan_pagination_show: "Tampilkan",
    penugasan_pagination_of: "dari",
    penugasan_pagination_activities: "kegiatan",
    penugasan_pagination_prev: "Sebelumnya",
    penugasan_pagination_next: "Selanjutnya",
    penugasan_modal_create_title: "Buat Penugasan Baru",
    penugasan_modal_edit_title: "Edit Penugasan Khusus",
    penugasan_modal_detail_title: "Detail Informasi Penugasan",
    penugasan_conflict_detected: "Bentrok jadwal terdeteksi",
    penugasan_related_activity: "Kegiatan terkait",
    penugasan_manage_agenda: "Kelola agenda",
    penugasan_pic_label: "Petugas (PIC)",
    penugasan_no_officer_db: "Belum ada petugas di database",
    penugasan_assignment_time: "Waktu penugasan",
    penugasan_coverage_location: "Lokasi liputan",
    penugasan_notes_instructions: "Catatan / instruksi",
    penugasan_optional: "(opsional)",
    penugasan_notes_ph: "Instruksi khusus liputan atau batas pengumpulan…",
    penugasan_save_task: "Simpan Penugasan",
    penugasan_delete_confirm_title: "Konfirmasi Hapus Penugasan",
    penugasan_delete_confirm_msg: "Apakah Anda yakin ingin menghapus penugasan",
    penugasan_delete_btn: "Hapus Penugasan",

    // Produksi & Review Page
    produksi_title: "Produksi Konten",
    produksi_subtitle: "Monitoring alur kerja produksi naskah berita, foto, video, dan desain grafis.",
    produksi_add_btn: "Produksi Baru",
    produksi_work_link: "Tautan Kerja / Aset",
    produksi_open_link: "Buka Link",
    produksi_start_date: "Mulai",
    produksi_end_date: "Selesai",
    review_title: "Review & Kontrol Kualitas Konten",
    review_subtitle: "Evaluasi draf hasil liputan, naskah berita, dan desain grafis sebelum diterbitkan ke publik.",
    review_badge_admin_portal: "Portal Admin SIMIKP",
    review_search_ph: "Cari kegiatan, jenis konten, lokasi, atau bidang...",
    review_tab_all: "Semua",
    review_tab_need_review: "Menunggu Review",
    review_tab_revision: "Perlu Revisi",
    review_tab_approved: "Disetujui",
    review_category_filter: "Kategori Agenda:",
    review_btn_preview: "Pratinjau Draf",
    review_btn_request_revision: "Minta Revisi",
    review_btn_edit_revision: "Ubah Catatan Revisi",
    review_btn_approve: "Setujui Konten",
    review_btn_approved_done: "Sudah Disetujui",
    review_notes_title: "Catatan Koreksi & Revisi dari Admin",
    review_no_tasks: "Tidak ada pengajuan konten yang sesuai filter review saat ini.",
    review_modal_revision_title: "Ajukan Catatan Koreksi & Revisi",
    review_modal_revision_ph: "Contoh: Tolong sesuaikan palet warna diagram dengan branding resmi Pemkot...",
    review_modal_send_btn: "Kirim Catatan Revisi",
    review_prahum_reader_title: "Meja Telaah Naskah Berita Humas",
    review_prahum_words: "Kata",
    review_prahum_copy_all: "Salin Seluruh Naskah",
    review_prahum_no_script: "Naskah Berita Belum Disetor",
    review_prahum_no_script_desc: "Petugas Pranata Humas belum menuliskan naskah berita untuk kegiatan ini. Anda dapat memberikan arahan atau meminta draf rilis melalui tombol Catatan Revisi di bawah.",
    review_prahum_request_rev_btn: "Minta Revisi Naskah",
    review_prahum_approve_btn: "Setujui Naskah (Siap Tayang)",
    review_curation_title: "Meja Kurasi Redaksi Foto & Video Liputan",
    review_curation_caption_label: "Keterangan / Caption Petugas:",
    review_curation_select_title: "Pilih Foto/Video untuk Bank Konten:",
    review_curation_selected_count: "Dipilih",
    review_curation_select_all: "Pilih Semua",
    review_curation_deselect_all: "Batalkan Pilihan",
    review_curation_request_rev_btn: "Minta Revisi Foto/Video",
    review_curation_approve_btn: "Setujui ke Bank Konten Utama",
    review_curation_no_files: "Berkas Liputan Belum Diunggah",
    review_curation_no_files_desc: "Petugas fotografer atau videografer belum mengunggah foto maupun video ke server internal untuk penugasan ini.",
    review_design_title: "Telaah Desain Grafis & Media Publikasi",
    review_design_notes_label: "Catatan Desainer / Editor:",
    review_design_download: "Unduh Berkas",
    review_design_request_rev_btn: "Minta Revisi Desain",
    review_design_approve_btn: "Setujui Desain ke Bank Konten Utama",
    review_design_no_files: "Berkas Desain Belum Diunggah",
    review_design_no_files_desc: "Petugas desainer grafis belum mengunggah berkas desain akhir untuk penugasan ini.",
    review_btn_read_script: "Baca & Telaah Naskah",
    review_btn_review_design: "Telaah Hasil Desain",
    review_btn_curation_table: "Meja Kurasi Foto & Video",
    review_btn_no_script_yet: "Naskah Belum Masuk",
    review_btn_no_design_yet: "Desain Belum Diunggah",
    review_btn_no_media_yet: "Foto/Video Belum Masuk",

    // Publikasi Page
    pub_title: "Publikasi Media & Kanal Informasi",
    pub_subtitle: "Jadwalkan dan distribusikan materi komunikasi publik ke website resmi dan media sosial.",
    pub_add_btn: "Publikasi Baru",
    pub_col_title: "Judul Konten",
    pub_col_channel: "Kanal Publikasi",
    pub_col_link: "Tautan Publikasi",
    pub_col_publish_date: "Tanggal Terbit",
    pub_col_views: "Tayangan / Interaksi",
    pub_col_status: "Status Publikasi",
    pub_modal_title: "Tambah Jadwal Publikasi Baru",
    pub_channel_website: "Website Resmi Pemkot",
    pub_channel_instagram: "Instagram (@pemkotbatu)",
    pub_channel_facebook: "Facebook Page",
    pub_channel_youtube: "YouTube Diskominfo",
    pub_channel_tiktok: "TikTok Pemkot",
    pub_status_scheduled: "Dijadwalkan",
    pub_status_published: "Diterbitkan",

    // Bank Konten Page
    bank_title: "Bank Konten",
    bank_subtitle: "Pusat penyimpanan & penemuan kembali aset dokumentasi liputan IKP Diskominfo.",
    bank_digital_archive_badge: "Arsip Digital",
    bank_upload_new_btn: "Unggah Berkas Baru",
    bank_upload_btn: "Unggah File Media",
    bank_search_ph: "Cari berdasarkan nama kegiatan, nomor strakom, atau petugas...",
    bank_filter_year: "Semua Tahun",
    bank_filter_category: "Semua Kategori",
    bank_sort_newest: "Terbaru",
    bank_sort_oldest: "Terlama",
    bank_storage_title: "Kapasitas Penyimpanan Server",
    bank_storage_used: "Terpakai",
    bank_storage_free: "Tersedia",
    bank_stat_total_folders: "Total Folder Kegiatan",
    bank_stat_total_photos: "Total Arsip Foto",
    bank_stat_total_videos: "Total Arsip Video",
    bank_stat_storage_used: "Kapasitas Terpakai",
    bank_filter_issue: "Isu:",
    bank_view_all_files: "Lihat Semua File",
    bank_folder_photos: "Foto",
    bank_folder_videos: "Video",
    bank_folder_files: "File",
    bank_open_folder: "Buka Folder & Pratinjau",
    bank_empty_folder: "Tidak ada folder kegiatan",
    bank_empty_folder_desc: "Tidak ada arsip kegiatan yang sesuai dengan kriteria filter.",
    bank_download_file: "Unduh File",
    bank_gallery_title: "Galeri Arsip Kegiatan",
    bank_download_all: "Unduh Semua File",
    bank_search_files_ph: "Cari nama file foto atau video...",

    // Laporan Page
    laporan_title: "Laporan & Statistik Produksi",
    laporan_subtitle: "Ringkasan metrik kinerja liputan, volume produksi konten, dan efektivitas komunikasi publik.",
    laporan_filter_period_title: "Filter Periode Laporan",
    laporan_filter_period_type: "Tipe Periode",
    laporan_filter_mode_month: "Per Bulan",
    laporan_filter_mode_quarter: "Per Triwulan (Quarter)",
    laporan_filter_mode_range: "Rentang Tanggal Custom",
    laporan_start_date: "Tanggal Mulai",
    laporan_end_date: "Tanggal Selesai",
    laporan_export_excel: "Ekspor Excel",
    laporan_export_pdf: "Cetak Laporan PDF",
    laporan_view_cards: "Card Kegiatan",
    laporan_view_table: "Pratinjau Tabel",
    laporan_summary_total_kegiatan: "Total Kegiatan Terdokumentasi",
    laporan_summary_total_konten: "Total Konten Diproduksi",
    laporan_summary_avg_time: "Rata-rata Waktu Produksi",
    laporan_summary_approval_rate: "Rasio Persetujuan Tepat Waktu",
    laporan_table_activity: "Nama Agenda Kegiatan",
    laporan_table_date: "Tanggal",
    laporan_table_prahum: "Prahum / Naskah",
    laporan_table_foto: "Foto",
    laporan_table_video: "Video",
    laporan_table_desain: "Desain",
    laporan_table_status: "Status Akhir",
    laporan_empty: "Tidak ada data produksi",
    laporan_empty_desc: "Belum ada laporan produksi pada periode filter ini.",
    laporan_detail_modal_title: "Rincian Penugasan & Output Kegiatan",
    laporan_detail_opd: "OPD Penyelenggara",
    laporan_detail_location: "Lokasi Acara",
    laporan_detail_date: "Tanggal Kegiatan",
    laporan_detail_assignments_list: "Daftar Penugasan Khusus Petugas",
    laporan_detail_no_assignments: "Belum ada rincian penugasan untuk kegiatan ini.",

    // Petugas & Member Pages
    anggota_title: "Daftar Anggota Tim",
    anggota_subtitle: "Kelola dan lihat daftar seluruh petugas lapangan SIMIKP",
    anggota_add_btn: "Tambah Anggota Baru",
    anggota_search_ph: "Cari berdasarkan nama atau PIC...",
    anggota_filter_type: "Semua Jabatan",
    anggota_status_active: "Aktif Bertugas",
    anggota_status_inactive: "Nonaktif",
    anggota_empty: "Tidak ada anggota",
    anggota_empty_desc: "Belum ada anggota yang terdaftar atau cocok dengan pencarian.",
    anggota_detail_title: "Detail Profil Petugas",
    anggota_delete_title: "Hapus Akun Petugas",
    anggota_delete_confirm: "Apakah Anda yakin ingin menghapus akun petugas ini dari sistem SIMIKP?",
    anggota_view_detail_btn: "Lihat Detail",
    tambah_petugas_title: "Form Tambah Petugas Lapangan Baru",
    tambah_petugas_subtitle: "Lengkapi data autentikasi dan spesialisasi bidang kerja anggota tim operasional baru.",
    tambah_petugas_back: "Kembali ke Daftar Anggota",
    tambah_petugas_sec_role: "Spesialisasi & Bidang Penugasan",
    tambah_petugas_sec_personal: "Data Pribadi & Kontak",
    tambah_petugas_sec_auth: "Autentikasi & Akun Sistem",
    tambah_petugas_field_program: "Bidang / Sektor Keahlian",
    tambah_petugas_field_name: "Nama Lengkap (Beserta Gelar)",
    tambah_petugas_field_email: "Alamat Email Kedinasan",
    tambah_petugas_field_password: "Kata Sandi Akun",
    tambah_petugas_field_gender: "Jenis Kelamin",
    tambah_petugas_field_nik: "NIK Pegawai",
    tambah_petugas_field_birth_place: "Tempat Lahir",
    tambah_petugas_field_birth_date: "Tanggal Lahir",
    tambah_petugas_field_photo: "Unggah Pas Foto Pegawai",
    tambah_petugas_submit_btn: "Simpan & Buat Akun Petugas",

    // Petugas Field Workspace
    petugas_dash_title: "Dashboard Petugas Lapangan",
    petugas_dash_subtitle: "Selamat datang di ruang kerja digital liputan Pemerintah Kota Batu.",
    petugas_stat_assigned: "Tugas Baru",
    petugas_stat_in_progress: "Sedang Dikerjakan",
    petugas_stat_need_revision: "Perlu Revisi",
    petugas_stat_completed: "Tugas Selesai",
    petugas_today_schedule: "Jadwal Liputan Hari Ini",
    petugas_btn_workspace: "Buka Ruang Kerja Penugasan",
    petugas_workspace_title: "Ruang Kerja & Pengumpulan Tugas",
    petugas_workspace_subtitle: "Perbarui status pengerjaan dan kirimkan link hasil liputan / materi konten.",
    petugas_upload_label: "Tautan Cloud / Drive Hasil Kerja",
    petugas_upload_ph: "Tempel link Google Drive / OneDrive / Folder hasil liputan...",
    petugas_submit_work_btn: "Kirim Hasil Kerja ke Admin",
    petugas_status_action_btn: "Perbarui Status Tugas",

    // Profile Page
    profile_title: "Profil Pengguna",
    profile_petugas_title: "Profil Petugas Lapangan",
    profile_subtitle: "Informasi akun dan identitas pengguna SIMIKP Pemerintah Kota Batu",
    officer_info: "Informasi Akun Pegawai",
    officer_info_desc: "Detail autentikasi dan hak akses SIMIKP",
    full_name: "Nama Lengkap",
    username_email: "Username / Email Akun",
    system_role: "Peran Sistem (Role)",
    field_sector: "Sektor Bidang Tugas",
    user_id: "ID Pengguna Sistem",
    copy_id: "Salin ID",
    id_copied: "ID Pengguna berhasil disalin ke clipboard!",
    opd_instance: "Instansi OPD",
    opd_name: "Diskominfo Kota Batu",
    pemkot_batu: "Pemerintah Kota Batu",
    task_sector: "Sektor Penugasan",
    production_line_active: "● Jalur Alur Produksi Aktif",
    operational_area: "Wilayah Operasional",
    batu_city_jt: "Kota Batu, Jawa Timur",
    among_tani: "Balaikota Among Tani",
    quick_access_officer: "Akses Cepat Petugas",
    quick_access_desc: "Navigasi cepat ke modul kerja Anda",
    view_update_task: "Lihat & perbarui progres tugas",
    content_archive_desc: "Arsip foto, video, & aset rilis",
    account_security: "Keamanan Akun",
    session_prefs_desc: "Preferensi sesi & notifikasi",
    user_session: "Sesi Masuk Pengguna",
    save_work_before_logout: "Pastikan menyimpan seluruh pekerjaan sebelum keluar dari aplikasi SIMIKP.",
    official_team_notice: "Akun ini terdaftar sebagai bagian dari tim operasional komunikasi publik resmi Pemerintah Kota Batu.",

    // Settings Page
    settings_title: "Pengaturan Akun",
    settings_subtitle: "Kelola keamanan kata sandi, identitas profil, preferensi notifikasi, dan tampilan sistem Anda.",
    tab_security: "Keamanan & Password",
    tab_security_desc: "Ubah kata sandi dan proteksi akun",
    tab_profile: "Data Profil & Kontak",
    tab_profile_desc: "Informasi nama, email, dan bidang",
    tab_notif: "Preferensi Notifikasi",
    tab_notif_desc: "Pengaturan pemberitahuan tugas",
    tab_appearance: "Tampilan & Tema",
    tab_appearance_desc: "Mode warna dan bahasa antarmuka",

    change_password: "Ubah Kata Sandi (Password)",
    change_password_desc: "Perbarui kata sandi secara berkala untuk menjaga keamanan akun Anda",
    current_password: "Kata Sandi Saat Ini",
    current_password_ph: "Masukkan kata sandi lama",
    new_password: "Kata Sandi Baru",
    new_password_ph: "Minimal 6 karakter kombinasi",
    confirm_new_password: "Konfirmasi Kata Sandi Baru",
    confirm_new_password_ph: "Ketik ulang kata sandi baru",
    password_strength: "Kekuatan Sandi:",
    save_new_password: "Simpan Kata Sandi Baru",
    password_saved_success: "Kata sandi akun Anda berhasil diperbarui!",
    password_match_error: "Konfirmasi password baru tidak cocok!",
    password_length_error: "Password baru minimal 6 karakter.",
    password_current_error: "Masukkan password saat ini untuk verifikasi.",

    edit_profile: "Edit Data Profil Pegawai",
    edit_profile_desc: "Perbarui nama tampilan, kontak, dan penyesuaian data diri Anda",
    full_name_label: "Nama Lengkap Pegawai",
    wa_phone_label: "Nomor WhatsApp / Kontak Tugas",
    sector_task_label: "Sektor Bidang Penugasan",
    sector_filter_desc: "Pilihan sektor menentukan filter penugasan dan antrean materi liputan yang masuk ke akun Anda.",
    profile_saved_success: "Data profil berhasil disimpan dan diperbarui!",

    notif_preferences: "Preferensi Pemberitahuan",
    notif_preferences_desc: "Tentukan bagaimana Anda ingin menerima update agenda dan instruksi liputan",
    notif_email_title: "Notifikasi Ringkasan Email",
    notif_email_desc: "Terima notifikasi rekap agenda dan rilis pers via email dinas",
    notif_browser_title: "Notifikasi Browser & Pop-up",
    notif_browser_desc: "Tampilkan banner pop-up saat ada penugasan baru yang masuk",
    notif_sound_title: "Efek Suara Notifikasi (Audio Alert)",
    notif_sound_desc: "Bunyikan denting lonceng saat menerima feedback atau persetujuan",
    notif_wa_title: "Pemberitahuan WhatsApp Tugas Mendesak",
    notif_wa_desc: "Kirim sinyal darurat penugasan langsung ke WhatsApp",

    appearance_lang_title: "Tampilan & Bahasa",
    appearance_lang_desc: "Sesuaikan kenyamanan visual dan bahasa aplikasi SIMIKP",
    color_theme_mode: "Mode Tema Warna",
    light_mode: "Mode Terang (Light)",
    light_mode_desc: "Tampilan bersih dengan latar cerah",
    dark_mode: "Mode Gelap (Dark Mode)",
    dark_mode_desc: "Tampilan elegan hemat daya & redup",
    active_now: "Sedang Aktif",
    choose_mode: "Pilih Mode",
    interface_lang: "Bahasa Antarmuka (Language)",
    need_help_title: "Butuh Bantuan Akun?",
    need_help_desc: "Jika mengalami kendala hak akses, lupa kata sandi lama, atau mutasi dinas, hubungi Admin Diskominfo Kota Batu.",

    // Login Page
    login_title: "Masuk ke Sistem",
    login_subtitle: "Silakan masukkan akun kedinasan Anda untuk mengakses dashboard SIMIKP.",
    login_welcome: "Selamat Datang di SIMIKP",
    login_hero_tagline: "Pemerintah Kota Batu • Diskominfo",
    login_hero_title: "Sistem Informasi Manajemen IKP",
    login_hero_desc: "Platform terpadu pengelolaan liputan, penugasan tim lapangan, produksi konten, dan diseminasi komunikasi publik Kota Batu.",
    login_feature_1: "Sinkronisasi Agenda & Penugasan Lapangan",
    login_feature_2: "Alur Kerja Produksi & Review Terstruktur",
    login_feature_3: "Arsip Dokumentasi & Bank Konten Digital",
    login_username: "Username atau Email",
    login_username_placeholder: "Masukkan username atau email",
    login_password: "Kata Sandi",
    login_password_placeholder: "Masukkan kata sandi akun Anda",
    login_forgot_password: "Lupa kata sandi?",
    login_forgot_password_info: "Untuk alasan keamanan kedinasan, reset kata sandi dapat diajukan langsung melalui Tim Administrator Diskominfo Kota Batu.",
    login_submit_btn: "Masuk ke Dashboard",
    login_submitting: "Memverifikasi Akun...",
    login_failed: "Autentikasi gagal. Mohon periksa kembali username dan kata sandi Anda.",
    login_footer_secured: "Terhubung dengan Server Diskominfo Pemerintah Kota Batu",
    login_demo_title: "Akun Pengujian / Demo:",
    login_demo_hint: "Password demo dapat diisi apa saja.",
    login_forgot_modal_title: "Lupa Kata Sandi Akun",
    login_forgot_modal_desc: "Masukkan alamat email yang terdaftar pada akun SIMIKP Anda. Kami akan mengirimkan tautan reset kata sandi resmi ke email tersebut.",
    login_forgot_email_label: "Alamat Email Terdaftar",
    login_forgot_email_ph: "contoh: nama@batukota.go.id / gmail.com",
    login_forgot_hint: "💡 Tautan pembuatan sandi baru akan dikirimkan otomatis ke inbox email Anda.",
    login_forgot_send_btn: "Kirim Tautan",
    login_forgot_sending: "Mengirim...",
    login_forgot_success_title: "Tautan Berhasil Dikirim!",
    login_forgot_success_desc: "Instruksi dan tautan untuk membuat kata sandi baru telah kami kirimkan ke:",
    login_forgot_success_note: "Silakan periksa kotak masuk (inbox) atau folder spam pada email Anda, lalu klik tombol tautan di dalamnya. Tautan berlaku selama 30 menit.",
    login_forgot_back_to_login: "Kembali ke Halaman Login",
  },

  en: {
    // Navigation & Common
    back: "Back",
    back_to_dashboard: "Back to Dashboard",
    back_to_profile: "Back to Profile",
    dashboard: "Dashboard",
    activities: "Activity Management",
    assignments: "Special Assignments",
    production: "Content Production",
    review_approval: "Review & Approval",
    media_pub: "Media Publication",
    content_bank: "Content Bank",
    reports_stats: "Reports & Statistics",
    member_list: "Member List",
    add_officer: "Add Officer",
    my_assignments: "My Assignments",
    available_agenda: "Available Agenda",
    profile: "Profile",
    profile_mine: "My Profile",
    settings: "Settings",
    account_settings: "Account Settings",
    logout: "Log Out",
    logout_confirm_title: "Confirm Log Out",
    logout_confirm_desc: "Are you sure you want to end your current session?",
    cancel: "Cancel",
    yes_logout: "Yes, Log Out",
    help: "Help",
    notifications: "Notifications",
    system_active: "SIMIKP System Active",
    verified_account: "Verified Account",
    save: "Save",
    saving: "Saving...",
    save_changes: "Save Changes",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    filter: "Filter",
    all: "All",
    status: "Status",
    actions: "Actions",
    details: "Details",
    close: "Close",
    success: "Success",
    error: "An Error Occurred",
    warning: "Warning",
    info: "Information",
    loading: "Loading...",
    confirm: "Confirm",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    deadline: "Deadline",
    location: "Location",
    date: "Date",
    month: "Month",
    year: "Year",
    notes: "Notes",
    upload: "Upload",
    download: "Download",
    preview: "Preview",
    views: "Views",
    active: "Active",
    pending: "Pending",
    done: "Done",
    in_progress: "In Progress",
    conflict: "Conflict",
    revision: "Revision",
    approved: "Approved",
    need_review: "Needs Review",
    select_all: "Select All",
    clear_filter: "Reset Filters",
    refresh: "Refresh",
    today: "Today",

    // Roles & Divisions
    role_super_admin: "Super Admin",
    role_ahli_pertama: "First Expert Officer",
    role_admin: "Admin",
    role_manager: "Manager",
    role_staff: "Staff",
    role_reviewer: "Reviewer",
    role_petugas: "Field Officer",
    bidang_ahli_pertama: "First Expert Functional Supervisor",
    bidang_prahum: "Public Relations / Script",
    bidang_foto: "Photography & Visuals",
    bidang_video: "Videography & Reels",
    bidang_desainer: "Graphic Design & Editor",
    bidang_reporter: "Field Reporter",
    bidang_kontributor: "News Contributor",
    ahli_supervision: "Expert Supervision & Sign-off",
    ahli_executive_dashboard: "First Expert Executive Panel",
    ahli_strategic_validation: "Strategic Review & Endorsement",
    ahli_sla_metrics: "SLA Performance & Script Validation",

    // Dashboard Page
    dash_total_activities_month: "Total Activities This Month",
    dash_tasks_in_progress: "Tasks in Progress",
    dash_content_ready_review: "Content Ready for Review",
    dash_published_success: "Published Successfully",
    dash_total_files_bank: "Total Files in Content Bank",
    dash_recent_tasks_deadline: "Recent Tasks & Approaching Deadlines",
    dash_activity_calendar: "Activity Calendar",
    dash_activity_calendar_desc: "Select a date to view activities scheduled for that day.",
    dash_view_all_activities: "View All Activities",
    dash_col_activity: "Activity Name",
    dash_col_content_type: "Content Type",
    dash_col_officer: "Officer",
    dash_col_organizer: "Organizer",
    dash_col_deadline: "Deadline",
    dash_col_status: "Status",
    dash_panel_prahum_title: "PR & Press Release",
    dash_panel_prahum_subtitle: "Field Coverage & News Article Scripting",
    dash_panel_foto_title: "PHOTO",
    dash_panel_foto_subtitle: "Visual Documentation & Press Photo Archive",
    dash_panel_video_title: "VIDEO & REELS",
    dash_panel_video_subtitle: "News Video Production & Social Media Clips",
    dash_panel_desain_title: "GRAPHIC DESIGNER",
    dash_panel_desain_subtitle: "Infographics, Banners & Social Visuals",
    dash_status_peliputan: "Coverage",
    dash_status_draft: "Draft Script",
    dash_status_siap_rilis: "Ready to Release",
    dash_status_take_shoot: "Shooting",
    dash_status_raw_photo: "Raw Footage",
    dash_status_editing: "Editing",
    dash_status_reels: "Reels / TikTok",
    dash_status_infografis: "Infographic Design",
    dash_status_banner: "Banner / Poster",
    dash_status_revisi_desain: "Design Revision",
    dash_activity_details: "Activity Details & Agenda",
    dash_no_activities_today: "No activities scheduled on this date.",
    dash_no_activities_db: "No scheduled activities found in the database.",
    dash_manage_in_activities: "Manage in Activity Management",
    dash_prod_workflow_status: "Production Workflow Status",
    dash_volume_per_opd: "Activity Volume per OPD Agency",
    dash_total_running_tasks: "Total ongoing tasks",

    // Kegiatan Page
    kegiatan_title: "Activity Agenda",
    kegiatan_subtitle: "Manage scheduled activities (One Activity = One Master Record)",
    kegiatan_add_btn: "Add Activity",
    kegiatan_add_modal_title: "Add New Activity",
    kegiatan_edit_modal_title: "Edit Activity Data",
    kegiatan_search_placeholder: "Search activity name...",
    kegiatan_filter_all_time: "All Time",
    kegiatan_filter_today: "Today",
    kegiatan_filter_tomorrow: "Tomorrow",
    kegiatan_filter_this_week: "This Week",
    kegiatan_col_title: "Activity Name",
    kegiatan_col_date: "Execution Date",
    kegiatan_col_location: "Location",
    kegiatan_col_opd: "Organizing Agency (OPD)",
    kegiatan_col_output: "Required Outputs",
    kegiatan_col_priority: "Priority",
    kegiatan_col_status: "Status",
    kegiatan_col_action: "Actions",
    kegiatan_form_title: "Activity Name",
    kegiatan_form_title_ph: "Example: Coordination Meeting...",
    kegiatan_form_date: "Execution Date",
    kegiatan_form_location_detail: "Execution Location Details",
    kegiatan_form_building: "Building / Room Name *",
    kegiatan_form_district: "District (Kecamatan)",
    kegiatan_form_subdistrict: "Subdistrict / Village",
    kegiatan_form_address: "Full Address (Optional)",
    kegiatan_form_opd: "Organizing Agency (OPD)",
    kegiatan_form_opd_ph: "Select or type OPD agency...",
    kegiatan_form_priority: "Priority",
    kegiatan_form_outputs_title: "Required Deliverables (By Role)",
    kegiatan_form_manage_outputs: "Manage Outputs",
    kegiatan_form_selected_count: "selected",
    kegiatan_form_related_assignments: "Related Special Assignments",
    kegiatan_form_add_assignment: "+ Add Assignment",
    kegiatan_form_no_assigned_staff: "No staff members assigned to this activity yet.",
    kegiatan_empty: "No activities found.",
    kegiatan_delete_confirm: "Delete this activity? This action cannot be undone.",
    kegiatan_manage_outputs_title: "Manage Activity Output Options",
    kegiatan_add_new_output_title: "Add New Output Type",
    kegiatan_output_name_label: "Output Type Name",
    kegiatan_output_name_ph: "Example: Live Streaming, Podcast, Press Release...",
    kegiatan_select_role_label: "Select Position / Person in Charge",
    kegiatan_reset_default_btn: "Reset to Default",
    kegiatan_finish_btn: "Done",
    kegiatan_current_outputs_list: "Current Output List",
    kegiatan_options_count: "Options",
    kegiatan_no_output_options: "No output options available",
    kegiatan_no_output_for_role: "No outputs yet",
    kegiatan_edit_output_title: "Edit & Move Output Type",
    kegiatan_move_to_other_role: "Move to Another Position",
    kegiatan_cal_subtitle: "Select a date to view or add new activities",

    // Penugasan Page
    penugasan_title: "Special Assignments",
    penugasan_subtitle: "Manage and monitor coverage task schedules for content staff in an organized manner.",
    penugasan_add_btn: "New Task",
    penugasan_search_ph: "Search activity, staff, content type...",
    penugasan_filter_bidang: "All Sectors / Divisions",
    penugasan_stat_total: "Total Assignments",
    penugasan_stat_progress: "In Progress",
    penugasan_stat_conflict: "Schedule Conflicts",
    penugasan_stat_done: "Completed Tasks",
    penugasan_tab_all: "All",
    penugasan_tab_in_progress: "In Progress",
    penugasan_tab_done: "Completed",
    penugasan_tab_pending: "Pending",
    penugasan_tab_conflict: "Conflict",
    penugasan_sort_label: "Sort by:",
    penugasan_sort_activity: "Activity",
    penugasan_sort_time: "Time",
    penugasan_sort_status: "Status",
    penugasan_col_officer: "Officer",
    penugasan_col_content_type: "Content Type",
    penugasan_col_time: "Time",
    penugasan_col_status: "Status",
    penugasan_col_action: "Actions",
    penugasan_add_officer_btn: "Add Officer",
    penugasan_officers_count: "officers",
    penugasan_empty: "No task assignments found",
    penugasan_empty_desc: "Try changing your tab filter or search keywords.",
    penugasan_bulk_selected: "selected:",
    penugasan_pagination_show: "Show",
    penugasan_pagination_of: "of",
    penugasan_pagination_activities: "activities",
    penugasan_pagination_prev: "Previous",
    penugasan_pagination_next: "Next",
    penugasan_modal_create_title: "Create New Assignment",
    penugasan_modal_edit_title: "Edit Special Assignment",
    penugasan_modal_detail_title: "Assignment Details",
    penugasan_conflict_detected: "Schedule conflict detected",
    penugasan_related_activity: "Related activity",
    penugasan_manage_agenda: "Manage agenda",
    penugasan_pic_label: "Assigned Officer (PIC)",
    penugasan_no_officer_db: "No officers found in database",
    penugasan_assignment_time: "Assignment time",
    penugasan_coverage_location: "Coverage location",
    penugasan_notes_instructions: "Notes / instructions",
    penugasan_optional: "(optional)",
    penugasan_notes_ph: "Specific coverage instructions or submission guidelines…",
    penugasan_save_task: "Save Assignment",
    penugasan_delete_confirm_title: "Confirm Delete Assignment",
    penugasan_delete_confirm_msg: "Are you sure you want to delete the assignment for",
    penugasan_delete_btn: "Delete Assignment",

    // Produksi & Review Page
    produksi_title: "Content Production",
    produksi_subtitle: "Monitor the production workflow for articles, photos, videos, and graphics.",
    produksi_add_btn: "New Production",
    produksi_work_link: "Work Link / Asset",
    produksi_open_link: "Open Link",
    produksi_start_date: "Start",
    produksi_end_date: "End",
    review_title: "Review & Quality Control",
    review_subtitle: "Evaluate coverage drafts, press articles, and graphics before public dissemination.",
    review_badge_admin_portal: "SIMIKP Admin Portal",
    review_search_ph: "Search activity, content type, location, or division...",
    review_tab_all: "All",
    review_tab_need_review: "Needs Review",
    review_tab_revision: "Needs Revision",
    review_tab_approved: "Approved",
    review_category_filter: "Agenda Category:",
    review_btn_preview: "Preview Draft",
    review_btn_request_revision: "Request Revision",
    review_btn_edit_revision: "Edit Revision Notes",
    review_btn_approve: "Approve Content",
    review_btn_approved_done: "Already Approved",
    review_notes_title: "Correction & Revision Notes from Admin",
    review_no_tasks: "No submitted content matches the review filter at this moment.",
    review_modal_revision_title: "Submit Correction & Revision Notes",
    review_modal_revision_ph: "Example: Please adjust chart color palette to official municipal branding...",
    review_modal_send_btn: "Send Revision Notes",
    review_prahum_reader_title: "PR Press Release Script Review Table",
    review_prahum_words: "Words",
    review_prahum_copy_all: "Copy Full Script",
    review_prahum_no_script: "No Press Script Submitted Yet",
    review_prahum_no_script_desc: "The PR staff has not submitted a press release script for this activity yet. You can provide directions or request a draft using the Revision Notes button below.",
    review_prahum_request_rev_btn: "Request Script Revision",
    review_prahum_approve_btn: "Approve Script (Ready to Publish)",
    review_curation_title: "Editorial Photo & Video Curation Desk",
    review_curation_caption_label: "Staff Description / Caption:",
    review_curation_select_title: "Select Photos/Videos for Content Bank:",
    review_curation_selected_count: "Selected",
    review_curation_select_all: "Select All",
    review_curation_deselect_all: "Deselect All",
    review_curation_request_rev_btn: "Request Photo/Video Revision",
    review_curation_approve_btn: "Approve to Main Content Bank",
    review_curation_no_files: "Coverage Files Not Yet Uploaded",
    review_curation_no_files_desc: "The assigned photographer or videographer has not uploaded media files to the internal server for this task yet.",
    review_design_title: "Graphic Design & Publication Review",
    review_design_notes_label: "Designer / Editor Notes:",
    review_design_download: "Download File",
    review_design_request_rev_btn: "Request Design Revision",
    review_design_approve_btn: "Approve Design to Main Content Bank",
    review_design_no_files: "Design Files Not Yet Uploaded",
    review_design_no_files_desc: "The assigned graphic designer has not uploaded the final design deliverable for this task yet.",
    review_btn_read_script: "Read & Review Script",
    review_btn_review_design: "Review Design Output",
    review_btn_curation_table: "Photo & Video Curation Desk",
    review_btn_no_script_yet: "Script Pending",
    review_btn_no_design_yet: "Design Pending",
    review_btn_no_media_yet: "Media Pending",

    // Publikasi Page
    pub_title: "Media Publication & Channels",
    pub_subtitle: "Schedule and distribute public communications to official websites and social media.",
    pub_add_btn: "New Publication",
    pub_col_title: "Content Title",
    pub_col_channel: "Publication Channel",
    pub_col_link: "Publication Link",
    pub_col_publish_date: "Publish Date",
    pub_col_views: "Views / Reach",
    pub_col_status: "Publication Status",
    pub_modal_title: "Schedule New Publication",
    pub_channel_website: "Official City Website",
    pub_channel_instagram: "Instagram (@pemkotbatu)",
    pub_channel_facebook: "Facebook Page",
    pub_channel_youtube: "Diskominfo YouTube",
    pub_channel_tiktok: "City TikTok",
    pub_status_scheduled: "Scheduled",
    pub_status_published: "Published",

    // Bank Konten Page
    bank_title: "Content Bank",
    bank_subtitle: "Central storage and retrieval for IKP Diskominfo coverage documentation assets.",
    bank_digital_archive_badge: "Digital Archive",
    bank_upload_new_btn: "Upload New Files",
    bank_upload_btn: "Upload Media Files",
    bank_search_ph: "Search by activity name, strakom number, or officer...",
    bank_filter_year: "All Years",
    bank_filter_category: "All Categories",
    bank_sort_newest: "Newest",
    bank_sort_oldest: "Oldest",
    bank_storage_title: "Server Storage Capacity",
    bank_storage_used: "Used",
    bank_storage_free: "Free",
    bank_stat_total_folders: "Total Activity Folders",
    bank_stat_total_photos: "Total Photo Archive",
    bank_stat_total_videos: "Total Video Archive",
    bank_stat_storage_used: "Storage Used",
    bank_filter_issue: "Topic:",
    bank_view_all_files: "View All Files",
    bank_folder_photos: "Photos",
    bank_folder_videos: "Videos",
    bank_folder_files: "Files",
    bank_open_folder: "Open Folder & Preview",
    bank_empty_folder: "No activity folders",
    bank_empty_folder_desc: "No archived activities match your filter criteria.",
    bank_download_file: "Download File",
    bank_gallery_title: "Activity Archive Gallery",
    bank_download_all: "Download All Files",
    bank_search_files_ph: "Search photo or video filename...",

    // Laporan Page
    laporan_title: "Production Reports & Analytics",
    laporan_subtitle: "Performance metrics summary, media production volume, and public communication impact.",
    laporan_filter_period_title: "Report Period Filter",
    laporan_filter_period_type: "Period Type",
    laporan_filter_mode_month: "Monthly",
    laporan_filter_mode_quarter: "Quarterly",
    laporan_filter_mode_range: "Custom Date Range",
    laporan_start_date: "Start Date",
    laporan_end_date: "End Date",
    laporan_export_excel: "Export Excel",
    laporan_export_pdf: "Print PDF Report",
    laporan_view_cards: "Activity Cards",
    laporan_view_table: "Table Preview",
    laporan_summary_total_kegiatan: "Documented Activities",
    laporan_summary_total_konten: "Produced Content Pieces",
    laporan_summary_avg_time: "Average Turnaround Time",
    laporan_summary_approval_rate: "On-Time Approval Rate",
    laporan_table_activity: "Agenda Name",
    laporan_table_date: "Date",
    laporan_table_prahum: "PR / Script",
    laporan_table_foto: "Photos",
    laporan_table_video: "Videos",
    laporan_table_desain: "Design",
    laporan_table_status: "Final Status",
    laporan_empty: "No production data",
    laporan_empty_desc: "No production records found for this period filter.",
    laporan_detail_modal_title: "Activity Assignment & Output Details",
    laporan_detail_opd: "Organizing Agency (OPD)",
    laporan_detail_location: "Event Location",
    laporan_detail_date: "Activity Date",
    laporan_detail_assignments_list: "Field Officer Assignments Breakdown",
    laporan_detail_no_assignments: "No assignment details recorded for this activity yet.",

    // Petugas & Member Pages
    anggota_title: "Team Member List",
    anggota_subtitle: "Manage and view all SIMIKP field coverage officers",
    anggota_add_btn: "Add New Member",
    anggota_search_ph: "Search by name or PIC ID...",
    anggota_filter_type: "All Positions",
    anggota_status_active: "Active on Duty",
    anggota_status_inactive: "Inactive",
    anggota_empty: "No members found",
    anggota_empty_desc: "No members are registered or match the search query.",
    anggota_detail_title: "Officer Profile Details",
    anggota_delete_title: "Delete Officer Account",
    anggota_delete_confirm: "Are you sure you want to remove this officer account from SIMIKP?",
    anggota_view_detail_btn: "View Details",
    tambah_petugas_title: "Add New Field Officer",
    tambah_petugas_subtitle: "Fill in the authentication details and job specialization for the new team member.",
    tambah_petugas_back: "Back to Member List",
    tambah_petugas_sec_role: "Specialization & Division",
    tambah_petugas_sec_personal: "Personal Data & Contact",
    tambah_petugas_sec_auth: "System Account Credentials",
    tambah_petugas_field_program: "Specialization Sector",
    tambah_petugas_field_name: "Full Name (With Titles)",
    tambah_petugas_field_email: "Official Email Address",
    tambah_petugas_field_password: "Account Password",
    tambah_petugas_field_gender: "Gender",
    tambah_petugas_field_nik: "Employee ID (NIK)",
    tambah_petugas_field_birth_place: "Birth Place",
    tambah_petugas_field_birth_date: "Birth Date",
    tambah_petugas_field_photo: "Upload Officer Portrait Photo",
    tambah_petugas_submit_btn: "Save & Create Officer Account",

    // Petugas Field Workspace
    petugas_dash_title: "Field Officer Dashboard",
    petugas_dash_subtitle: "Welcome to your digital coverage workspace for Batu City Government.",
    petugas_stat_assigned: "New Tasks",
    petugas_stat_in_progress: "In Progress",
    petugas_stat_need_revision: "Needs Revision",
    petugas_stat_completed: "Completed Tasks",
    petugas_today_schedule: "Today's Coverage Schedule",
    petugas_btn_workspace: "Open Task Workspace",
    petugas_workspace_title: "Task Workspace & Submission",
    petugas_workspace_subtitle: "Update your progress status and submit work links or media assets.",
    petugas_upload_label: "Cloud / Drive Link for Deliverables",
    petugas_upload_ph: "Paste Google Drive / OneDrive link with your deliverables...",
    petugas_submit_work_btn: "Submit Deliverables to Admin",
    petugas_status_action_btn: "Update Task Status",

    // Profile Page
    profile_title: "User Profile",
    profile_petugas_title: "Field Officer Profile",
    profile_subtitle: "Account credentials and user identity for Batu City Government SIMIKP",
    officer_info: "Officer Account Information",
    officer_info_desc: "SIMIKP authentication and access permissions details",
    full_name: "Full Name",
    username_email: "Account Username / Email",
    system_role: "System Role",
    field_sector: "Field Sector Assignment",
    user_id: "System User ID",
    copy_id: "Copy ID",
    id_copied: "User ID copied to clipboard!",
    opd_instance: "Regional Agency (OPD)",
    opd_name: "Diskominfo Batu City",
    pemkot_batu: "Batu City Government",
    task_sector: "Assignment Sector",
    production_line_active: "● Active Production Pipeline",
    operational_area: "Operational Jurisdiction",
    batu_city_jt: "Batu City, East Java",
    among_tani: "Among Tani City Hall",
    quick_access_officer: "Officer Quick Access",
    quick_access_desc: "Fast navigation to your work modules",
    view_update_task: "View & update task progress",
    content_archive_desc: "Photo, video & release asset archive",
    account_security: "Account Security",
    session_prefs_desc: "Session & notification preferences",
    user_session: "User Login Session",
    save_work_before_logout: "Please ensure all work is saved before logging out from SIMIKP.",
    official_team_notice: "This account is registered as part of the official public communication operational team of Batu City Government.",

    // Settings Page
    settings_title: "Account Settings",
    settings_subtitle: "Manage your password security, profile identity, notification preferences, and interface display.",
    tab_security: "Security & Password",
    tab_security_desc: "Change password and protect your account",
    tab_profile: "Profile & Contact",
    tab_profile_desc: "Name, email, and assignment details",
    tab_notif: "Notification Preferences",
    tab_notif_desc: "Task alerts and update settings",
    tab_appearance: "Display & Theme",
    tab_appearance_desc: "Color modes and interface language",

    change_password: "Change Password",
    change_password_desc: "Regularly update your password to keep your account secure",
    current_password: "Current Password",
    current_password_ph: "Enter your old password",
    new_password: "New Password",
    new_password_ph: "Minimum 6 characters combination",
    confirm_new_password: "Confirm New Password",
    confirm_new_password_ph: "Re-type your new password",
    password_strength: "Password Strength:",
    save_new_password: "Save New Password",
    password_saved_success: "Your account password has been updated successfully!",
    password_match_error: "New password confirmation does not match!",
    password_length_error: "New password must be at least 6 characters.",
    password_current_error: "Please enter your current password for verification.",

    edit_profile: "Edit Officer Profile",
    edit_profile_desc: "Update your display name, contact information, and personal details",
    full_name_label: "Officer Full Name",
    wa_phone_label: "WhatsApp Number / Work Contact",
    sector_task_label: "Task Assignment Sector",
    sector_filter_desc: "Your chosen sector determines the assignment filters and incoming media coverage queue.",
    profile_saved_success: "Profile data has been saved and updated successfully!",

    notif_preferences: "Notification Preferences",
    notif_preferences_desc: "Choose how you would like to receive agenda updates and coverage briefings",
    notif_email_title: "Email Summary Notifications",
    notif_email_desc: "Receive agenda recaps and press release briefs via official email",
    notif_browser_title: "Browser & Pop-up Notifications",
    notif_browser_desc: "Show pop-up banner alerts when new tasks are assigned to you",
    notif_sound_title: "Audio Alerts & Sound Effects",
    notif_sound_desc: "Play a notification chime when receiving feedback or approvals",
    notif_wa_title: "WhatsApp Urgent Task Alerts",
    notif_wa_desc: "Send urgent assignment alerts directly to WhatsApp",

    appearance_lang_title: "Display & Language",
    appearance_lang_desc: "Customize visual comfort and interface language in SIMIKP",
    color_theme_mode: "Color Theme Mode",
    light_mode: "Light Mode",
    light_mode_desc: "Clean layout with a bright background",
    dark_mode: "Dark Mode",
    dark_mode_desc: "Sleek low-light & battery-saving mode",
    active_now: "Active",
    choose_mode: "Select Mode",
    interface_lang: "Interface Language",
    need_help_title: "Need Account Help?",
    need_help_desc: "If you encounter permission issues, forgot your old password, or underwent official mutation, please contact Diskominfo Batu City Admin.",

    // Login Page
    login_title: "Sign In to System",
    login_subtitle: "Please enter your official credentials to access the SIMIKP dashboard.",
    login_welcome: "Welcome to SIMIKP",
    login_hero_tagline: "Batu City Government • Diskominfo",
    login_hero_title: "Public Information Management System",
    login_hero_desc: "Integrated platform for coverage management, field team assignments, content production, and public communication dissemination in Batu City.",
    login_feature_1: "Agenda & Field Task Synchronization",
    login_feature_2: "Structured Production & Review Workflow",
    login_feature_3: "Digital Documentation & Content Archive",
    login_username: "Username or Email",
    login_username_placeholder: "Enter username or email",
    login_password: "Password",
    login_password_placeholder: "Enter your account password",
    login_forgot_password: "Forgot password?",
    login_forgot_password_info: "For security reasons, password resets can be requested directly through the Batu City Diskominfo Administrator team.",
    login_submit_btn: "Sign In to Dashboard",
    login_submitting: "Verifying Account...",
    login_failed: "Authentication failed. Please verify your username and password.",
    login_footer_secured: "Connected to Batu City Government Diskominfo Server",
    login_demo_title: "Test / Demo Accounts:",
    login_demo_hint: "You can enter any password for demo accounts.",
    login_forgot_modal_title: "Forgot Account Password",
    login_forgot_modal_desc: "Enter the email address registered with your SIMIKP account. We will send an official password reset link to that email.",
    login_forgot_email_label: "Registered Email Address",
    login_forgot_email_ph: "example: name@batukota.go.id / gmail.com",
    login_forgot_hint: "💡 A link to create a new password will be sent automatically to your email inbox.",
    login_forgot_send_btn: "Send Link",
    login_forgot_sending: "Sending...",
    login_forgot_success_title: "Link Sent Successfully!",
    login_forgot_success_desc: "Instructions and link to create a new password have been sent to:",
    login_forgot_success_note: "Please check your inbox or spam folder, then click the link inside. The link is valid for 30 minutes.",
    login_forgot_back_to_login: "Back to Sign In",
  },
};

export type TranslationKey = keyof typeof translations.id;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey | string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "id",
  setLanguage: () => {},
  t: (key, fallback) => (translations.id as Record<string, string>)[key] || fallback || key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem("simikp-lang") as Language | null;
      if (saved === "id" || saved === "en") {
        return saved;
      }
    } catch {
      // ignore
    }
    return "id";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("simikp-lang", lang);
    } catch {
      // ignore
    }
  };

  const t = (key: TranslationKey | string, fallback?: string): string => {
    const dict = (translations[language] || translations.id) as Record<string, string>;
    const defaultDict = translations.id as Record<string, string>;
    return dict[key] ?? defaultDict[key] ?? fallback ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
